services:
    laravel-argonaut-dto:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-argonaut-dto
        tty: true
        environment:
            SERVICE_NAME: laravel-argonaut-dto
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - yorcreative

networks:
    yorcreative:
        driver: bridge

